project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "aulas/*.qmd"

website:
  title: "Full Cycle"

format:
  revealjs:
    theme: default
    slide-number: true
    transition: slide
    incremental: false
    footer: "Full Cycle"
